[package]
name = "rp-simple-1"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Release please simple 1"

[dependencies]
rp-simple-3.workspace = true
risc_v_simulator = { git = "https://github.com/matter-labs/air_compiler" }
